services:
  auth-service:
    image: kenesparta/lgr-auth-service
    environment:
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    restart: "always"
    ports:
      - "3000:3000"
      - "50051:50051"
