services:
  auth-service:
    image: kenesparta/lgr-auth-service
    environment:
      JWT_SECRET: ${JWT_SECRET}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CAPTCHA_SITE_KEY: ${CAPTCHA_SITE_KEY}
      CAPTCHA_SECRET_KEY: ${CAPTCHA_SECRET_KEY}
    restart: "always"
    ports:
      - "3000:3000"
      - "50051:50051"
    depends_on:
      - db

  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local