### Variables
@baseUrl =https://auth.rustybootcamp.xyz

### Health check
GET {{baseUrl}}/health-check
Content-Type: application/json

### Sign Up! 201
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "email": "{{$uuid}}@example.com",
  "password": "password123",
  "requires2FA": false
}

### Sign Up! 400
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "email": "{{$uuid}}example.com",
  "password": "password123",
  "requires2FA": false
}

### Sign Up! 400
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "email": "{{$uuid}}@example.com",
  "password": "1",
  "requires2FA": false
}

### Sign Up! 409
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "email": "user001@example.com",
  "password": "password123",
  "requires2FA": false
}

### Sign Up! 409
POST {{baseUrl}}/signup
Content-Type: application/json

{
  "email": "user001@example.com",
  "password": "password123",
  "requires2FA": false
}