name: Feature Branch | Build, Test and Push to Docker

on:
  push:
    branches:
      # we can change this name conventions, T means task and S means sprint
      - feat-S[0-9]+T[0-9]+
      # the Q is for side quests
      - feat-S[0-9]+Q[0-9]+
      - bugfix-S[0-9]+T[0-9]+
      - hotfix-S[0-9]+T[0-9]+
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          .cargo
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: Install Rust
      run: rustup update stable && rustup default stable

    - name: Build and test app-service code
      working-directory: .
      run: |
        cargo build --verbose
        cargo test --verbose

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Prepare Docker tag
      id: prep
      run: |
        BRANCH_NAME=$(echo ${GITHUB_REF_NAME} | sed 's/[^a-zA-Z0-9._-]/-/g' | tr '[:upper:]' '[:lower:]')
        echo "tag=${BRANCH_NAME}" >> $GITHUB_OUTPUT

    - name: Build and push Docker images
      uses: docker/bake-action@v2.3.0
      with:
        push: true
        files: |
          compose.yml
          compose.override.yml
        set: |
          *.cache-from=type=gha
          *.cache-to=type=gha,mode=max
          *.tags=kenesparta/lgr-auth-service:${{ steps.prep.outputs.tag }}
